routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PublicController@homepage')->name('home');
Route::get('img/{id}', 'PublicController@img')->name('image');
Route::get('verify', 'PublicController@verify')->name('verify');
Route::get('order/{id}', 'PublicController@order')->name('order');

Route::post('add', 'PublicController@add_cart')->name('add');
Route::post('verify-user', 'PublicController@verify_user')->name('verify_user');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('admin');
Route::get('/img/{id}/delete', 'HomeController@deleteImage')->name('delete-img');

Route::resources([
    'transaction' => 'TransactionsController',
    'products' => 'ProductsController',
    'category' => 'CategoryController',
    'users' => 'UsersController',
    'orders' => 'OrdersController',
    'cart' => 'CartController',
]);

resources/views/admin/edit.blade.php
@extends('admin.index')

@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Edit Transaction</h3>
				</div>
				<div class="panel-body">
					
					<div class="row">
						<div class="col-md-6">
						
							<div class="table-responsive">
								<table class="table table-hover table-bordered">
									<thead>
										<tr>
											<th>Name</th>
											<th>Details</th>
										</tr>
									</thead>
									<tbody>
										<tr>
											<td>Transaction ID:</td>
											<td>{{ strtoupper($trans->transaction_code) }}</td>
										</tr>
										<tr>
											<td>Name:</td>
											<td>{{ $trans->first_name.' '.$trans->last_name }}</td>
										</tr>
										<tr>
											<td>Address:</td>
											<td>{{ $trans->address }}</td>
										</tr>
										<tr>
											<td>Phone:</td>
											<td>{{ $trans->phone }}</td>
										</tr>
										<tr>
											<td>Order Status:</td>
											<td>
												<form action="{{ route('transaction.update', $trans->id) }}" method="POST">
		                        					{{ method_field('PATCH') }}
		                        					@csrf
		                        					<div class="input-group">
		                        						<select class="form-control" name="status">
		                        							<option value="hold"{{ $trans->status=='hold' ? ' selected':'' }}>On Hold</option>
		                        							<option value="pending"{{ $trans->status=='pending' ? ' selected':'' }}>Pending</option>
		                        							<option value="processing"{{ $trans->status=='processing' ? ' selected':'' }}>Processing</option>
		                        							<option value="delivered"{{ $trans->status=='delivered' ? ' selected':'' }}>Delivered</option>
		                        							<option value="failed"{{ $trans->status=='failed' ? ' selected':'' }}>Canceled / Failed</option>
		                        						</select>
		                        						<span class="input-group-btn">
		                        							<button class="btn btn-success" type="submit">Update Status</button>
		                        						</span>
		                        					</div><!-- /input-group -->
												</form>
											</td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>
						<div class="col-md-6">
							<div class="table-responsive">
								<table class="table table-hover table-bordered">
									<thead>
										<tr>
											<th>Name</th>
											<th>Quantity</th>
											<th>Price</th>
											<th>Total</th>
										</tr>
									</thead>
									<tbody>
										<?php $total = 0; $count = 0; ?>
										@foreach($carts as $cart)
										<tr>
											<td>{{ $cart->product_name }}</td>
											<td>{{ $cart->quantity }}</td>
											<td>₱{{ number_format($cart->price,2,'.',',') }}</td>
											<td>₱{{ number_format( ($cart->price*$cart->quantity) ,2,'.',',') }}</td>
										</tr>
										<?php $total = $total+$cart->price; $count = $count+$cart->quantity; ?>
										@endforeach	
										<tr class="success">
											<td><b>TOTAL:</b></td>
											<td class="quantity">{{$count}}</td>
											<td></td>
											<td><b class="grand">₱{{ number_format($total,2,'.',',') }}</b></td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>
					</div>

				</div>
			</div>

		</div>
	</div>	
</div>
@endsection

resources/views/admin/index.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Yuan's Kitchen Garden</title>
        <link rel="stylesheet" href="{{asset('css/bootstrap.min.css')}}">
        <link href="{{asset('css/font-awesome.min.css')}}" rel="stylesheet">
        <link href="{{asset('css/switchery.min.css')}}" rel="stylesheet">
        <link href="{{asset('css/toastr.min.css')}}" rel="stylesheet">
        <link href="{{asset('summernote/summernote.min.css')}}" rel="stylesheet">
        @yield('styles')
    </head>
    <body>
        <nav class="navbar navbar-inverse" style="border-radius: 0;">
            <div class="container-fluid">
                <a class="navbar-brand" href="{{ url('/') }}">Yuan's Kitchen Garden</a>
                <ul class="nav navbar-nav">
                    <li @if(Route::current()->getName() == 'admin') class="active" @endif>
                        <a href="{{ route('admin') }}">Orders</a>
                    </li>
                    <li @if(Route::current()->getName() == 'products.index') class="active" @endif>
                        <a href="{{ route('products.index') }}">Products</a>
                    </li>
                    <li @if(Route::current()->getName() == 'category.index') class="active" @endif>
                        <a href="{{ route('category.index') }}">Categories</a>
                    </li>
                    <li @if(Route::current()->getName() == 'users.index') class="active" @endif>
                        <a href="{{ route('users.index') }}">Users</a>
                    </li>
                    <li><a href="{{ route('users.edit', auth()->user()->id) }}">Settings</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{{ route('logout') }}"
                           onclick="event.preventDefault();
                                         document.getElementById('logout-form').submit();">
                            {{ __('Logout') }}
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
        @yield('title')
        @yield('content')

        <script src="{{asset('js/jquery-3.4.1.min.js')}}"></script>
        <script src="{{asset('js/bootstrap.min.js')}}"></script>
        <script src="{{asset('js/switchery.min.js')}}"></script>
        <script src="{{asset('js/toastr.min.js')}}"></script>
        <script src="{{asset('summernote/summernote.min.js')}}"></script>
        <script src="{{asset('js/scripts.js')}}"></script>
        @yield('scripts')
        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">@csrf</form>
        @foreach ( $errors->all() as $message )
            <script>toastr.warning('{{ $message }}', 'Error!')</script>
        @endforeach
        @if(session('success'))
            <script>toastr.success('{{ session('success') }}', 'Success!')</script>
        @endif
        @if(session('error'))
            <script>toastr.error('{{ session('error') }}', 'Error!')</script>
        @endif
    </body>
</html>

resources/views/admin/transactions.blade.php
@extends('admin.index')

@section('content')
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Transactions</h3>
				</div>
				<div class="panel-body">
					@if($orders->count())

						<div class="table-responsive">
							<table class="table table-hover">
								<thead>
									<tr>
										<th>Option</th>
										<th>Transaction Code</th>
										<th>Status</th>
										<th>Address</th>
										<th>Phone</th>
										<th>Customer Name</th>
										<th>Amount</th>
									</tr>
								</thead>
								<tbody>
									@foreach($orders as $order)
									<tr class="{{ $status[$order->status] }}">
										<td><a class="btn btn-default btn-xs" href="{{ route('transaction.edit',$order->id) }}">View details</a></td>
										<td>{{ strtoupper($order->transaction_code) }}</td>
										<td><span class="badge">{{ ucfirst($order->status) }}</span></td>
										<td>{{ $order->address }}</td>
										<td>{{ $order->phone }}</td>
										<td>{{ $order->first_name.' '.$order->last_name }}</td>
										<td>₱{{ number_format($order->total_price,2,'.',',') }}</td>
									</tr>
									@endforeach
								</tbody>
							</table>
						</div>

						{!! $orders->render() !!}

					@else
						<div class="alert alert-info">
							<strong>Oops</strong> There are no records to show at the moment.
						</div>
					@endif
				</div>
			</div>

		</div>
	</div>	
</div>
@endsection